#!/bin/bash
# METHOD QM
# ID1D4DA86E557E6CC0E5B5F87ADADB0670
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c3c4
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

