#!/bin/bash
# METHOD QM
# IDC3EB15A9532734693FAB18BBE6ECE552
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c3
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

