#!/bin/bash
# METHOD QM
# ID55F8228AB7AFC6CB488540CEEC745361
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c2c5c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

