#!/bin/bash
# METHOD QM
# ID54339F7AE0C2BCD7FFAFF0C490AFB3B2
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c3c4
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

