#!/bin/bash
# METHOD QM
# ID9093B42E81A53B6DF3641B4230D7CB02
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c3c4
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

