#!/bin/bash
# METHOD QM
# ID2A3924366836F0A71A15440EC3FC480A
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c5c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

