#!/bin/bash
# METHOD QM
# IDB19F9F250E5C6A6BA1901917E4B758A3
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c3c4c5
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

