#!/bin/bash
# METHOD QM
# IDC939FB977D47CDF9305624712F191FFE
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c2c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

