#!/bin/bash
# METHOD QM
# IDF171DF9A4588D950D755B0FB773CCE34
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c3c5c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

