#!/bin/bash
# METHOD QM
# ID16C9F07B29B3EA779662F7CFC820456A
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c3c5c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

