#!/bin/bash
# METHOD QM
# IDC517F87F4B12461AA0C01F09EDBF5D7C
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c2c3c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

