#!/bin/bash
# METHOD QM
# IDEE552F44A59FD9E63F2FC5B48626788E
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c2c3c4c5
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

