#!/bin/bash
# METHOD QM
# ID4B4E7C77DE4710B6A7CE3DBDC3B15317
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c2c3
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

