#!/bin/bash
# METHOD QM
# ID995F66004EE17B9FD7F844DD00E1300A
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c2c3c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

