#!/bin/bash
# METHOD QM
# IDC9F6D53D4195921D28813CE5A849AC9D
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c3c5
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

