#!/bin/bash
# METHOD QM
# ID55BBE3EDABD8DC54BCB8E0284F3E1F81
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c3c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

