#!/bin/bash
# METHOD QM
# IDAC3085613C047D5BC32AD32565559F01
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c2c3c4c5c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

