#!/bin/bash
# METHOD QM
# ID77A26440148F5D819E1285D035CB9EFD
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

