#!/bin/bash
# METHOD QM
# ID3C0D7F5BCC34461B1AEE637F5BBBFAC6
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c2c4
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

