#!/bin/bash
# METHOD QM
# IDEB41BD464412C4F81B82474E1F52BC5B
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c2c5
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

