#!/bin/bash
# METHOD QM
# IDD58554E5150F2AD2E44DA390435E98E3
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c4c5
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

