#!/bin/bash
# METHOD QM
# IDD58554E5150F2AD2E44DA390435E98E3
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c4c5
prog=lammps
proton=F

 # ---- Script ----

			[ $prog != 'nwchem' ] && exit;
			[ $proton == 'T' ]&& exit;

			N=$(echo $molecule | wc -c)
			[ $N != 9 ]&& exit;  # cXcY... 8 + 1 (\n)

			mv energy.dat energy_old.dat
			echo > energy.dat

