#!/bin/bash
# METHOD QM
# IDFBE51B47775B6BA8255C80F74F548BE6
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c3c4c5
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

