#!/bin/bash
# METHOD QM
# IDD18E1A9201CC32F60483A3FD3A09CB02
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c2c5
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

