#!/bin/bash
# METHOD QM
# ID5A5BB93B63C885D550A6C56FA51333D2
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c2c3c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

