#!/bin/bash
# METHOD QM
# IDFE2B562B37FC5AD2EDCAB356B9B585B6
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

