#!/bin/bash
# METHOD QM
# ID97F29988A2F9CA993D4A1C61497283F6
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c5
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

