#!/bin/bash
# METHOD QM
# IDCA2FBDF58734916EF6D480FDE23742DC
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c3c5c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

