#!/bin/bash
# METHOD QM
# ID7FEDB8C9146A5AE2146DFEF0BCE3B734
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c2
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

