#!/bin/bash
# METHOD QM
# ID62776EE29243620DA348CD2D04B7108D
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c2c3c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

