#!/bin/bash
# METHOD QM
# ID51644C914A51D926EFF92E8AC4B7E9C6
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c2c4c5c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

