#!/bin/bash
# METHOD QM
# ID272D60B474B2EA5E79618DB26E2AF292
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c3
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

