#!/bin/bash
# METHOD QM
# ID554B6D17E96BB75140BF86EEDF04E3B9
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c2c5
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

