#!/bin/bash
# METHOD QM
# IDBCB656313357A06290ED0EE82E3DA296
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c5
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

