#!/bin/bash
# METHOD QM
# IDE0EA692CE9A8A5EE6ACC9A368E531D7E
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c5
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

