#!/bin/bash
# METHOD QM
# IDB49356D5D8EF2EDF40E025E7FDEF0D15
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c2c5c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

