#!/bin/bash
# METHOD QM
# IDB8F046A9BD728327E4CAAF1D9E9B065D
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c2c4c5
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

