#!/bin/bash
# METHOD QM
# ID6C2A404960857646B74800348276EB8A
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c2c3
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

