#!/bin/bash
# METHOD QM
# ID8A3AF3C86E92A6BD9CFCDF0F04E65805
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c4c5
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

