#!/bin/bash
# METHOD QM
# IDE0BCC5B7269C71990C6430D9246984C8
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c2c3
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

