#!/bin/bash
# METHOD QM
# ID3114BE4CDA008416CB33D3F01CCDCD9A
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c3c5
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

