#!/bin/bash
# METHOD QM
# IDFA9A92B26952C1D2D0BBE9AA7C04410D
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c3c4c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

