#!/bin/bash
# METHOD QM
# IDFAC49707FD1E1DB356FD37DD2154A895
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c2c3c4
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

