#!/bin/bash
# METHOD QM
# ID651F6C25B66EDC8722FA586AA17ACF17
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c2c3c4c5
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

