#!/bin/bash
# METHOD QM
# ID651F6C25B66EDC8722FA586AA17ACF17
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c2c3c4c5
prog=lammps
proton=T

 # ---- Script ----
			N=$( cat energy.dat | wc -w )
		
			[ $N -gt 0 ] && exit;

			rm -f energy.dat

			if [ $prog == 'nwchem' ]; then
				echo 6-31G > basis.dat
				./run

			fi


