#!/bin/bash
# METHOD QM
# ID1990303903953FCF16F08E58BB0E3018
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c3c4
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

