#!/bin/bash
# METHOD QM
# ID19F5EC51DFCE2221A9889C00BDDDF418
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c4c5c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

