#!/bin/bash
# METHOD QM
# IDA84A1B5DFB8D3FA785A1252E16F02436
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c3c4c5
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

