#!/bin/bash
# METHOD QM
# ID4907F84A9E02F7810D03D90B4858AF14
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c3c4c5
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

