#!/bin/bash
# METHOD QM
# ID53D023EBE172B8895C4AD5C7D433F4E2
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c2c3c5
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

