#!/bin/bash
# METHOD QM
# IDD0C4A4FF4D6D6FBD1C60C28B4F3BF8E3
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c2c4
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

