#!/bin/bash
# METHOD QM
# IDE9D61B7DBDEAC38B4AB588F180ACDEA8
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c3c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

