#!/bin/bash
# METHOD QM
# ID749CF9FCAAA23791355A26D9EA9C5E71
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c5
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

