#!/bin/bash
# METHOD QM
# ID7293C2EFD4CF49D13CA13B72101EAF8A
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c2c3c5
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

