#!/bin/bash
# METHOD QM
# ID4D5F0D56351E07D808E0F841B54C5099
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c2c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

