#!/bin/bash
# METHOD QM
# ID0967BB072C7DFA4A569BC91F4A865A79
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c2c4
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

