#!/bin/bash
# METHOD QM
# ID80FC34DDADB1C9F26D95B78C942B8F50
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c2c3
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

