#!/bin/bash
# METHOD QM
# IDD626E0DF254F0276D673E9B5E4F92A65
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c2c3c4
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

