#!/bin/bash
# METHOD QM
# IDC093618793A3915EF041667FF07C2403
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c2c5c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

