#!/bin/bash
# METHOD QM
# IDE314A3D6C7D70478DBD305FE44B93BC8
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

