#!/bin/bash
# METHOD QM
# ID028B6E10832C15EFC1BBDDE0BDE2318F
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c3c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

