#!/bin/bash
# METHOD QM
# IDED30161BA4A908E7330166AD7619BF59
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c2c4c5
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

