#!/bin/bash
# METHOD QM
# ID1B34AD4C3BE66A6D53768B6E8BA32006
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c2c3c5
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

