#!/bin/bash
# METHOD QM
# IDE447F88FC7577A6FF928113CA9ED9257
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c3c4c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

