#!/bin/bash
# METHOD QM
# ID4553D669EE1791AE85027FB89FAD5BDA
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c2c4
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

