#!/bin/bash
# METHOD QM
# ID3904B25B6309BED3618586CF75292BD3
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c2c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

