#!/bin/bash
# METHOD QM
# IDC1CB2D3246F997263C45FDC407B64B22
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c2
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

