#!/bin/bash
# METHOD QM
# ID890A8CE3AF47B96E39D2F5B7A750CA4C
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

