#!/bin/bash
# METHOD QM
# ID57313BAFA6DA92B946F10129BD7721D3
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c3c4c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

