#!/bin/bash
# METHOD QM
# ID0E8491A8F58080F6ED2A837369F8C107
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c2
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

