#!/bin/bash
# METHOD QM
# IDFC99E7786D3012541385A45436A889A0
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c4c5
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

