#!/bin/bash
# METHOD QM
# ID62F1AB92E9B58F0F9C55C842BB373FB6
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c2
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

