#!/bin/bash
# METHOD QM
# ID639F6C4DBAEAEA80471D7730A68C69A8
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c2c3c4c5c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

