#!/bin/bash
# METHOD QM
# ID5F3FDC941C351EA880C552F52E4074C5
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c2c5
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

