#!/bin/bash
# METHOD QM
# ID1B7FEBBAC1D8324E0C95C64AAC44931A
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c4
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

