#!/bin/bash
# METHOD QM
# IDDA79D1B5C77CCC888CA8D48ACB3BDE0B
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c5c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

