#!/bin/bash
# METHOD QM
# ID2B4BC8F49D6A75E8DC0DF39BE9FCEAC9
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c2c3c4
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

