#!/bin/bash
while [ $# -gt 0 ]; 
do
  var=$(echo $1 | gawk -F= '{print $1}')
  val=$(echo $1 | gawk -F= '{print $2}')

  isnumeric=$( echo print $val+0 | python 2>/dev/null | wc -l ) 

  [ $isnumeric == 0 ]&& val='"'$val'"';
  echo  's@SED:'$(./toupper $var)':\([^;]*\);@'$val'@g'

  shift
done

echo 's@SED:\([^:]*\):\([^;]*\);@\2@g'
