#!/bin/bash
# METHOD QM
# IDFECE58CD571D130DA525384CB2C43302
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c4c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

