#!/bin/bash
# METHOD QM
# IDDA75B0C3DF8744D1B109FA592F91D59B
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c3c4c5
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

