#!/bin/bash
# METHOD QM
# ID6EB58BCB407908B944C9E81075FEBC4D
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c2c3c4c5c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

