#!/bin/bash
# METHOD QM
# ID0B9789CE1AD873DED8C9DA0D6C04EE1E
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c3
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

