#!/bin/bash
# METHOD QM
# IDEC64365D9CE9C6EC7CE3C2754847717C
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c5c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

