#!/bin/bash
# METHOD QM
# IDB7FC8E4D58971274C6881DA8586DD688
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c4
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

