#!/bin/bash
# METHOD QM
# ID2F164C18AC3478DAB8E30D2AE8455681
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c2c3
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

