#!/bin/bash
# METHOD QM
# ID2F164C18AC3478DAB8E30D2AE8455681
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c2c3
prog=lammps
proton=T

 # ---- Script ----

			[ $prog != 'nwchem' ] && exit;
			[ $proton == 'T' ]&& exit;

			N=$(echo $molecule | wc -c)
			[ $N != 9 ]&& exit;  # cXcY... 8 + 1 (\n)

			mv energy.dat energy_old.dat
			echo > energy.dat

