#!/bin/bash
# METHOD QM
# ID5E3C8F6F309F3C6D83DFF57B93B5BF45
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c3c5c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

