#!/bin/bash
# METHOD QM
# IDFDF0E239AA0F19046248A617D2DE0898
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c4c5c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

