#!/bin/bash
# METHOD QM
# ID6D4E5B6C9552C2BDDC93BCDA82BB0213
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c3c4c5
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

