#!/bin/bash
# METHOD QM
# ID0785CEA35CA247229D54A91C7101E1EC
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c2
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

