#!/bin/bash
# METHOD QM
# IDB47391DBDC4D6D517C98E9985FCAAA6F
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c2c4c5c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

