#!/bin/bash
# METHOD QM
# IDA69EA5D1DF650A3F70E47952EC78F48E
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c4c5
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

