#!/bin/bash
# METHOD QM
# ID177FD008C8A492FA60E4790A5BB50BC6
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c4
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

