#!/bin/bash
# METHOD QM
# ID6370E920D36B8DC3A6B5CB0DA816A771
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c2c3c4
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

