#!/bin/bash
# METHOD QM
# ID756D00F593B589430FD6EEA3501BF6EB
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c5
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

