#!/bin/bash
# METHOD QM
# IDC1320779FB3D93517F174A139DAFA6FE
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c2c5
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

