#!/bin/bash
# METHOD QM
# IDD92438062B1D6B68E22DA4789F3DC800
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c2c3c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

