#!/bin/bash
# METHOD QM
# IDB6E565A19EF5829224CC63FF98738447
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c2c5c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

