#!/bin/bash
# METHOD QM
# ID30B45F1E3EEA54611E8C6FE0FC4A3D98
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c3c5
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

