#!/bin/bash
# METHOD QM
# ID8FEB118C4FCF971ABE0573D3359C8B60
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c2c3c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

