#!/bin/bash
# METHOD QM
# IDBF7CF32A36B67982D6970D5E1414A487
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c2c3c4c5
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

