#!/bin/bash
# METHOD QM
# ID770EA90B793909EBD625EAE914ED98B1
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c5c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

