#!/bin/bash
# METHOD QM
# ID6BB724B50F1BE9EE06A93DC969B460C6
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c2c3
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

