#!/bin/bash
# METHOD QM
# ID2878868448D16AD8D1306B3BA3E8FF89
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c2c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

