#!/bin/bash
# METHOD QM
# ID5F35DCB85599101E6EE01EAAB02F89AE
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c4c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

