#!/bin/bash
# METHOD QM
# IDF32619288C7966E841DBD5BE59BBE9ED
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c3c4
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

