#!/bin/bash
# METHOD QM
# IDA682261EC44D6890C61E854EDDED17D0
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c2c3c5c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

