#!/bin/bash
# METHOD QM
# ID88B458C97BD8909B04E2F12927481C33
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c2c4c5
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

