#!/bin/bash
# METHOD QM
# IDC59293D62FCCB069967FA543C730D747
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c3c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

