#!/bin/bash
# METHOD QM
# IDD3AE3DECA218EC950EC2BC1CD72A43D2
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c4c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

