#!/bin/bash
# METHOD QM
# IDF94B5DC8FE1713B5617252BCE79B6719
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c4c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

