#!/bin/bash
# METHOD QM
# ID4CA0D602926478AC6F1C12B651A427A6
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c2c3c5
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

