#!/bin/bash
# METHOD QM
# IDA6BCE09B51465BCCE8F083515D83BBF0
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c2c3
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

