#!/bin/bash
# METHOD QM
# ID287584444031ECC2318B8144C3E5BF38
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c3c4c5c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

