#!/bin/bash
# METHOD QM
# IDC36B2742D9C237D696D3E7824A4DEC37
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c2c5
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

