#!/bin/bash
# METHOD QM
# ID460BB32682EA1E3F57772D7D3205A842
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c2c4c5c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

