#!/bin/bash
# METHOD QM
# IDAD0B715EB626C636299BA76038AB4664
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c3c4c5c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

