#!/bin/bash
# METHOD QM
# ID99BA56EF96C2EAD99805EC1A347190FB
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c2c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

