#!/bin/bash
# METHOD QM
# ID756F6E4D37019B467DA47FA1947CC106
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c2c4
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

