#!/bin/bash
# METHOD QM
# IDF081D8425F15ED9197A4163FC0F2B25E
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c3c4c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

