#!/bin/bash
# METHOD QM
# ID88B32CC50E9534962AD1564F13B9B8BE
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c2c3c4c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

