#!/bin/bash
# METHOD QM
# ID8649B38CA250B9EFA11B9AFB4033CF64
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c3c4
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

