#!/bin/bash
# METHOD QM
# ID552989EB3626A51BF19847B162008B29
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c3
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

