#!/bin/bash
# METHOD QM
# ID43E9EF3CFB6F881C179355C42C259195
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c2c5c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

