#!/bin/bash
# METHOD QM
# IDCEBDD1DD6F3637DB6353EC9323265474
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c2
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

