#!/bin/bash
# METHOD QM
# IDC5249F43064CA71541F0940D9BD1F16A
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c4
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

