#!/bin/bash
# METHOD QM
# IDE3DF0F86D154A88916CE91C37BD2B918
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c2c3c4c5
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

