#!/bin/bash
# METHOD QM
# ID03B08D69EBFBE29AA416D203B5A46D79
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c3c5c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

