#!/bin/bash
# METHOD QM
# IDA5883F8AB48B88D927E37C5AB1584339
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c4
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

