#!/bin/bash
# METHOD QM
# ID10565F8F6E730B80516CAECEE7002C49
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c2c3c4c5c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

