#!/bin/bash
# METHOD QM
# ID981862CB7AB8982BF0C4031115BAA028
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c2c3c4c5
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

