#!/bin/bash
# METHOD QM
# IDADB93DA249C649AE7952C9308E5A1C2C
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c3c5
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

