#!/bin/bash
# METHOD QM
# ID2BDD9121D03275E8D9C74F6A07E9A37A
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c2c3c5
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

