#!/bin/bash
# METHOD QM
# ID86A0D5C83FA31F0EAA37E3CE8FF0E15A
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

