#!/bin/bash
# METHOD QM
# ID22A35C2D388616ECFC2ED7DF65CC8071
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c2c4c5
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

