#!/bin/bash
# METHOD QM
# ID3EA37656464D413917B533C63FCDDCA5
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c4c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

