#!/bin/bash
# METHOD QM
# ID00EEB84CD260DDF0676EE71CC5F7C2D1
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c2c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

