#!/bin/bash
# METHOD QM
# ID096E7FAEF202E8FD7C81002AF2F959C4
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c3c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

