#!/bin/bash
# METHOD QM
# ID64D70EDF3DBCEC9F15C8097135F64AE9
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c3c4c5c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

