#!/bin/bash
# METHOD QM
# IDFC82E5F791C2EAD5A7DC012DD6E569A3
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c2c4c5c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

