#!/bin/bash
# METHOD QM
# ID8E8D404EB503795FF1C98BAB302120F5
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c5
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

