#!/bin/bash
# METHOD QM
# ID1220FA327F7D9DC11A609B22406AB31D
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c3
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

