#!/bin/bash
# METHOD QM
# IDCF47AF137672D2BA7B9B4B438C74E03B
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

