#!/bin/bash
# METHOD QM
# ID9DD9606D9431AD7530D338D7F555D843
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c2c3c4c5
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

