#!/bin/bash
# METHOD QM
# IDF6A47724AE367497D1A1926F15712DB7
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c2c3c4c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

