#!/bin/bash
# METHOD QM
# ID00691DC6F49B72BDFABD8ADB0BDF552C
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c3c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

