#!/bin/bash
# METHOD QM
# ID70C59189B8D4860B1ADE5B7576D2EC0B
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c2c4c5c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

