#!/bin/bash
# METHOD QM
# ID7325E3B82E3E631D0D636725AB819C8D
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

