#!/bin/bash
# METHOD QM
# IDE4F96261E59C6820AE51A4152A175691
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c4
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

