#!/bin/bash
# METHOD QM
# IDE4F96261E59C6820AE51A4152A175691
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c4
prog=lammps
proton=T

 # ---- Script ----

			echo $FOLDER
			echo $prog $molecule $proton

			if [ -f energy.dat ]; then
				echo energy.dat exists! skiping the calculation! To re-start the calculation - run clear
			else	
		
				tic=$(date +%s)
				[ -f basis.dat ]&& basis=$(cat basis.dat);	
				./run_$prog cluster.xyz $basis
				cp E_${prog}_cluster.dat energy.dat
				toc=$(date +%s)
				echo $((toc-tic)) >> time.dat
				echo calculated in $((toc-tic)) s 

			fi

