#!/bin/bash
# METHOD QM
# ID44D30D2E06FA68F007B9E17D00667201
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c2c3c4c5c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

