#!/bin/bash
# METHOD QM
# ID3600815CB045D1E78951A5807B300BE5
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c3
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

