#!/bin/bash
# METHOD QM
# ID3600815CB045D1E78951A5807B300BE5
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c3
prog=lammps
proton=F

 # ---- Script ----

			echo $FOLDER
			echo $prog $molecule $proton

			if [ -f energy.dat ]; then
				echo energy.dat exists! skiping the calculation! To re-start the calculation - run clear
			else	
		
				tic=$(date +%s)
				[ -f basis.dat ]&& basis=$(cat basis.dat);	
				./run_$prog cluster.xyz $basis
				cp E_${prog}_cluster.dat energy.dat
				toc=$(date +%s)
				echo $((toc-tic)) >> time.dat
				echo calculated in $((toc-tic)) s 

			fi

