#!/bin/bash
# METHOD QM
# IDB9EBBF7A3C4A1F0905AA3B208FC6F9D5
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c3c5
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

