#!/bin/bash
# METHOD QM
# ID025350754E4AFA6E47B23344DFB71122
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c3c4c5c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

