#!/bin/bash
# METHOD QM
# IDBA3626DF7CC44D7E070E914A32FA3E92
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c2
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

