#!/bin/bash
# METHOD QM
# ID114252BD1B50AF09C9F7AB11500285AB
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c5c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

