#!/bin/bash
# METHOD QM
# ID05E081A992AD29486A803AAC37680100
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c3c5
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

