#!/bin/bash
# METHOD QM
# IDCD06EC23596490FC8268EC822EF4E5CA
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c3c4c5c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

