#!/bin/bash
# METHOD QM
# ID756B6E00FED19795E30283478C690762
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c4
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

