#!/bin/bash
# METHOD QM
# ID95CD74B6E1CEEF2BEE5ECF6386341444
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c3c4c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

