#!/bin/bash
# METHOD QM
# ID899A458D1ED51DD32EDBA6149C21BB6A
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c4c5c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

