#!/bin/bash
# METHOD QM
# IDA6EAE6B02EE4D96A4A2893056EA5EB64
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c2c3c4c5
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

