#!/bin/bash
# METHOD QM
# IDAAACC62602C461CC062E28D934AB67D4
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c3
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

