#!/bin/bash
# METHOD QM
# IDE61061FC17304FCDECCC430D9F5950EB
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

