#!/bin/bash
# METHOD QM
# ID0F8282079858AA2BE0AE6A612C2A00A6
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c2c5c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

