#!/bin/bash
# METHOD QM
# ID64673EC39A0EFB1E7DCC3E6755A8A932
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c2c4c5
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

