#!/bin/bash
# METHOD QM
# IDB1E073424D4D1EE33A830ACE332070DC
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c2c3c4c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

