#!/bin/bash
# METHOD QM
# IDB0777BF930EA98242D68DB5E17858F93
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c2c4c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

