#!/bin/bash
# METHOD QM
# IDE6C7AFC4C8662F2FA288BC8BB97CE809
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c2c3c5c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

