#!/bin/bash
# METHOD QM
# ID1D16F6B55FFDCD1D9A254B76980EE118
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c2c4c5c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

