#!/bin/bash
# METHOD QM
# ID7CBD4B79E015B5D6958745492B45E735
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c2c4c5c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

