#!/bin/bash
# METHOD QM
# ID0D54BA8853998AE2C18E4DD8B6CDB695
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c3c4c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

