#!/bin/bash
# METHOD QM
# IDFF955A08A3B678D9B7A79AAF1018E868
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c5c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

