#!/bin/bash
# METHOD QM
# ID785C59FE2AA287F77FD1C89078989FEB
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c4c5c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

