#!/bin/bash
# METHOD QM
# ID76A90821CC9C65C2DBFF3CCD6FBF7061
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c2c3c5c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

