#!/bin/bash
# METHOD QM
# ID94356AA1F132AA0B568A872CEC1F7C07
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c3c4c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

