#!/bin/bash
# METHOD QM
# IDD7978A4F2167806FB2EAE597F6138218
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c4c5
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

