#!/bin/bash
# METHOD QM
# ID2FA5B8D0BA8EDA662C53D68F430452FF
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c3c5c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

