#!/bin/bash
# METHOD QM
# ID58CB9574A250C5561109DEDAD40695F7
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c4c5
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

