#!/bin/bash

mkdir -p nwchem_neutral

for f in $(moldb_getRef clusters.chain prog=nwchem,proton=F); 
do
   mol=$(cat $f/PARAMETERS | grep molecule | gawk -F = '{print $2}')
   echo $mol
   mkdir -p nwchem_neutral/$mol
   cp $f/*  nwchem_neutral/$mol
done


mkdir -p nwchem_proton

for f in $(moldb_getRef clusters.chain prog=nwchem,proton=T); 
do
   mol=$(cat $f/PARAMETERS | grep molecule | gawk -F = '{print $2}')
   echo $mol
   mkdir -p nwchem_proton/$mol
   cp $f/*  nwchem_proton/$mol
done

# ----------------------------

mkdir -p abinit_neutral

for f in $(moldb_getRef clusters.chain prog=abinit,proton=F); 
do
   mol=$(cat $f/PARAMETERS | grep molecule | gawk -F = '{print $2}')
   echo $mol
   mkdir -p abinit_neutral/$mol
   cp $f/*  abinit_neutral/$mol
done


mkdir -p abinit_proton

for f in $(moldb_getRef clusters.chain prog=abinit,proton=T); 
do
   mol=$(cat $f/PARAMETERS | grep molecule | gawk -F = '{print $2}')
   echo $mol
   mkdir -p abinit_proton/$mol
   cp $f/*  abinit_proton/$mol
done


