#!/bin/bash

mkdir -p water_pairs

for f in $(moldb_getRef neutral_pair.chain prog=lammps); 
do
   mol=$(cat $f/PARAMETERS | grep molecule | gawk -F = '{print $2}')
   echo $mol
   mkdir -p water_pairs/$mol
   cp $f/*  water_pairs/$mol
done


