#!/bin/bash

B=0.5291772108

cat $1 | grep atom | wc -l
if [ $# -ge 2 ]; then
  echo $2
else
  echo "system converted from runner system"
fi

cat $1 | grep atom | gawk '{print $5" "$2*'$B'" "$3*'$B'" "$4*'$B'}'

