#!/usr/bin/python

import sys;


Narg=len(sys.argv)

if Narg<3:
   print "usage:  select_oxygens  file.xyz  coma_separated_oxygen_indeces > output.xyz "
   quit()

fname=sys.argv[1];
oxy_str = sys.argv[2].split(',');

oxy_list=[];
for s in oxy_str:
   oxy_list.append(int(s));

print oxy_list
#print sys.argv

#if [ $# -lt 2 ]; then

#  echo usage:  select_oxygens  file.xyz  coma_separated_oxygen_indeces '>' output.xyz
#  echo selects the molecules which has the given oxygens
#  exit

#fi


