#!/bin/bash

ox_id=$1
L=$2
R=$3

if [ $# -lt 3 ]; then

   echo usage:  select_neighb  id  box_length  radius 
   exit

fi


tail -n+3 water.xyz | gawk '{ print $2" "$3" "$4 }' > water.coors

cat > centrify.m <<EOL

function X = centrify

  
  X0 = load('water.coors');
  N = size(X0,1);

  Iox = (1:3:N);
  X0ox = X0(Iox,:);

  X = X0 - ones(N,1) * X0ox($ox_id,:) ;
  
  for i=1:3
    
    I1 = find(X(Iox,i) < -$L/2);
    I2 = find(X(Iox,i) > $L/2);

    II1 = [ 3*I1 - 2; 3*I1 - 1; 3*I1 ];
    II2 = [ 3*I2 - 2; 3*I2 - 1; 3*I2 ];  

    X( II1 , i) =  X(II1,i) + $L;
    X( II2 ,i) =  X(II2,i) - $L;
  end

EOL


cat > neighb.m << EOL

function X = neighb(X0,R)

   
   D = sqrt( sum(X0(1:3:end,:).^2,2));
   I0 = find(D<R);
   [DD,ID] = sort(D(I0));
   I = I0(ID);
%   II = [ 3*I - 2; 3*I-1; 3*I];
  Nox = size(I,1);
  II=zeros(3*Nox,1);
  II(1:3:end) = 3*I-2;
  II(2:3:end) = 3*I-1;
  II(3:3:end) = 3*I;
   X = X0(II,:);

EOL

cat > select_and_save.m <<EOL

X0 = centrify;
X = neighb(X0,$R);

save -ascii selected.coors X
EOL

octave -q select_and_save.m

N=$(cat selected.coors | wc -l)

echo $N
echo Selected waters in $R angstroems

tail -n+3 water.xyz | head -n$N | gawk '{print $1}' > selected.atomnames

paste selected.atomnames selected.coors
