#!/bin/bash

export MOLDB_ROOT=$(pwd)
export MOLDB_PROJECTS=$MOLDB_ROOT/Projects
export MOLDB_BIN=$MOLDB_ROOT/bin

export PYTHONPATH=$PYTHONPATH:$MOLDB_BIN

echo "Insert the following lines to your ~/.bashrc file !"
echo
echo export MOLDB_ROOT=$(pwd)
echo 'export MOLDB_PROJECTS=$MOLDB_ROOT/Projects'
echo 'export MOLDB_BIN=$MOLDB_ROOT/bin'
echo
echo export PYTHONPATH=$PYTHONPATH:$MOLDB_BIN

