#!/bin/bash
# METHOD QM
# ID0B674EAC56336091858636D4E9185DEE
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c2c4c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

