#!/bin/bash
# METHOD QM
# ID9765F54FA1B75F25FA5BCD3A827EBDB6
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c2c4c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

