#!/bin/bash
# METHOD QM
# ID3920F77327648544F0389FC4C24F50A1
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

