#!/bin/bash
# METHOD QM
# ID7CC436D6A1DD63DDDCC71EF5F5B3602B
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c2c4c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

