#!/bin/bash
# METHOD QM
# IDB74BF4CC26D72637E607C8DDAC650126
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c4c5c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

