#!/bin/bash
# METHOD QM
# ID1164C59A5818F6CBFE92F34F540380BE
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c3
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

