#!/bin/bash
# METHOD QM
# ID5A074DEB4C3FE61B673EF80223C9BFF6
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c2c3c4
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

