#!/bin/bash
# METHOD QM
# ID3D99FC4ECBE6A511EC1426F74F3B4127
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c5c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

