#!/bin/bash
# METHOD QM
# ID53CA017894A225B2D3858D8444D3BE49
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c2c4c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

