#!/bin/bash
# METHOD QM
# IDE50EA07FE8908FFB669F3ADCADFDED82
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c3c4c5
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

