#!/bin/bash
# METHOD QM
# IDC1287B69CE8A858DCFE516C7455E85A8
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c4c5c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

