#!/bin/bash
# METHOD QM
# ID6A9C1074A678D295F19F1C7BD6289689
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c2c4c5
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

