#!/bin/bash
# METHOD QM
# ID7CB4D106960F7B32AF7CAFF76967E1B3
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c2c4c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

