#!/bin/bash
# METHOD QM
# IDA164D6CC3A81DDF59D4E3BBE505AA35B
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c2c3c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

