#!/bin/bash
# METHOD QM
# IDFA94910D9C8B5F4F403A71EC4D5D80AD
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c2c3c5c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

