#!/bin/bash
# METHOD QM
# ID6AC98656B41607CCD684543F61F1B83A
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c4c5
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

