#!/bin/bash
# METHOD QM
# ID030DDDCCC945350F476F4C3C46C5E8E3
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c2c3c5c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

