#!/bin/bash
# METHOD QM
# ID4073A60272DEFD4817EFB3241A1F4A44
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c4c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

