#!/bin/bash
# METHOD QM
# IDCE701BC5321BEBA8CDCDD369310ED458
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c4c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

