#!/bin/bash
# METHOD QM
# ID5EF17D3E52CEB915F760AD47502AA81B
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c3c5
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

