#!/bin/bash
# METHOD QM
# ID482614574A4D44AEA605857B76881EC3
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c3c4c5
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

