#!/bin/bash
# METHOD QM
# ID482614574A4D44AEA605857B76881EC3
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c3c4c5
prog=lammps
proton=T

 # ---- Script ----

			[ $prog != 'nwchem' ] && exit;
			[ $proton == 'T' ]&& exit;

			N=$(echo $molecule | wc -c)
			[ $N != 9 ]&& exit;  # cXcY... 8 + 1 (\n)

			mv energy.dat energy_old.dat
			echo > energy.dat

