#!/bin/bash
# METHOD QM
# IDB102416FDDE2AB9D065CC0C0CE89E3AB
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c2c3c5c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

