#!/bin/bash
# METHOD QM
# IDE1C4F896EC4DF8F83F1969DBCC78E921
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c2c5
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

