#!/bin/bash
# METHOD QM
# IDA1DBA8775CA2C89CEED78E4E37BA4F01
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c2c4c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

