#!/bin/bash
# METHOD QM
# ID8DEDD80BA08C881ED6414DFD140A2EA1
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c2c3c4
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

