#!/bin/bash
# METHOD QM
# ID007BCB880D485001A2B51B9A27667503
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c3c5
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

