#!/bin/bash
# METHOD QM
# ID7CEF92548A23FBCC185F5814A8CD0B61
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c2c5c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

