#!/bin/bash
# METHOD QM
# IDCBDAFBEE4646891A94E893AA38A78B46
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c2c4c5
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

