#!/bin/bash
# METHOD QM
# IDCBDAFBEE4646891A94E893AA38A78B46
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c2c4c5
prog=lammps
proton=F

 # ---- Script ----
			N=$( cat energy.dat | wc -w )
		
			[ $N -gt 0 ] && exit;

			rm -f energy.dat

			if [ $prog == 'nwchem' ]; then
				echo 6-31G > basis.dat
				./run

			fi


