#!/bin/bash
# METHOD QM
# ID27C7D624C38330325136DD8054B3453F
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c3c4
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

