#!/bin/bash
# METHOD QM
# ID1D31FF25126721B835A6F5C03160BEF5
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c3c5c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

