#!/bin/bash
# METHOD QM
# IDBF8ED63E769A1424766F4551D020A73F
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c2c4c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

