#!/bin/bash
# METHOD QM
# ID8DCFAE0ED87614DB13A2CE3E938B0CB4
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c2c3c4
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

