#!/bin/bash
# METHOD QM
# IDAF2BCEE14D4F9A587F22AC9788C1A756
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c2c3c4
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

