#!/bin/bash
# METHOD QM
# ID9F4DB7C4F3F2E2CA3EAA455ABE428420
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c2c3c4c5
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

