#!/bin/bash
# METHOD QM
# ID8A9B12AE306070DFFA49814D6809E569
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c2c3c4c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

