#!/bin/bash
# METHOD QM
# ID8A3E08941AEFF132E8DC051F9DB134B8
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c5c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

