#!/bin/bash
# METHOD QM
# IDB776702BBCDF767BA677BFF3896005C4
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c3c4c5c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

