#!/bin/bash
# METHOD QM
# IDB233D981CB50492D726E14F2027D8A31
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c2c3c5
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

