#!/bin/bash
# METHOD QM
# ID1D820BCF864672C3E2D076AEE152E14C
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c5
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

