#!/bin/bash
# METHOD QM
# ID72D4843F3FBB5DAD0937E2BF34DFD136
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

