#!/bin/bash
# METHOD QM
# IDB7ED1DE69A3A0BA587537F85440B89B9
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c2c3c5
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

