#!/bin/bash
# METHOD QM
# ID182C8FD45EC9320042DEAD9F80E71E01
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

