#!/bin/bash
# METHOD QM
# IDE3C36F7C7A191C0E13B01D908EFE63B5
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c2c3c5
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

