#!/bin/bash
# METHOD QM
# ID14FE04F611A168D63ECAEC80908F9A30
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c2c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

