#!/bin/bash
# METHOD QM
# IDDAE6E42911362434F81CBC16E5C683EB
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

