#!/bin/bash
# METHOD QM
# IDD7106C9F0649BACC9B454727E9948197
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c3c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

