#!/bin/bash
# METHOD QM
# IDD2461C2FE9DB9076D82B9AB4F95624DC
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c3c5c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

