#!/bin/bash
# METHOD QM
# IDF2128CF8C52058ABE9DB814F1B232A57
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c2c5
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

