#!/bin/bash
# METHOD QM
# ID0227CAC7E688BDF2C7A82A9E90082995
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c2
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

