#!/bin/bash
# METHOD QM
# ID89A87BBEC1989DC560F399C1CF94C7FB
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c4c5c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

