#!/bin/bash
# METHOD QM
# IDCA317E31C30B62E25F015D6E563E25D3
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c2c3c4c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

