#!/bin/bash
# METHOD QM
# IDCA317E31C30B62E25F015D6E563E25D3
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c2c3c4c6
prog=lammps
proton=T

 # ---- Script ----
			N=$( cat energy.dat | wc -w )
		
			[ $N -gt 0 ] && exit;

			rm -f energy.dat

			if [ $prog == 'nwchem' ]; then
				echo 6-31G > basis.dat
				./run

			fi


