#!/bin/bash
# METHOD QM
# IDF4D10216C27F574D5C30FA4C853E0759
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c2c4c5c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

