#!/bin/bash
# METHOD QM
# IDF4D10216C27F574D5C30FA4C853E0759
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c2c4c5c6
prog=lammps
proton=F

 # ---- Script ----

			[ $prog != 'nwchem' ] && exit;
			[ $proton == 'T' ]&& exit;

			N=$(echo $molecule | wc -c)
			[ $N != 9 ]&& exit;  # cXcY... 8 + 1 (\n)

			mv energy.dat energy_old.dat
			echo > energy.dat

