#!/bin/bash
# METHOD QM
# IDE7DD6F55DB28A49B3325E68F2F716319
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c2c5c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

