#!/bin/bash
# METHOD QM
# ID2B4B697494A1DC76D6A661E778A79F45
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c2c4
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

