#!/bin/bash
# METHOD QM
# IDB4FEE05E5B92E7566F46044FC8482E46
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c4c5c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

