#!/bin/bash
# METHOD QM
# IDECFDF3EEA9FFE720B80A854201A94E2C
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c3c4
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

