#!/bin/bash
# METHOD QM
# IDECFDF3EEA9FFE720B80A854201A94E2C
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c3c4
prog=lammps
proton=F

 # ---- Script ----
			N=$( cat energy.dat | wc -w )
		
			[ $N -gt 0 ] && exit;

			rm -f energy.dat

			if [ $prog == 'nwchem' ]; then
				echo 6-31G > basis.dat
				./run

			fi


