#!/bin/bash
# METHOD QM
# ID13DD52E410028250A346378A22490034
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c2c3c5c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

