#!/bin/bash
# METHOD QM
# IDC80CDAAAABB332F8F5A82A9AF93C61FD
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c4c5
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

