#!/bin/bash
# METHOD QM
# ID1E5448C99239298E723A462A9DD59490
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c4c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

