#!/bin/bash
# METHOD QM
# IDE1E7BED4D593799A1968CFE30E2B9245
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c2c3
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

