#!/bin/bash
# METHOD QM
# ID685FE46F60D7A717823B07118A21C7BD
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c3c4c5c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

