#!/bin/bash
# METHOD QM
# IDA36DCC2C5612DED678974419EF7AFAC7
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c2c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

