#!/bin/bash
# METHOD QM
# IDA6F86DB29BB4BEDEB04CC6C33C612FF4
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c2c4
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

