#!/bin/bash
# METHOD QM
# ID5A404EF2BDBFE20920BCFAC3FECCB96F
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c5
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

