#!/bin/bash
# METHOD QM
# ID3353229038FBC5D36ED8E424522D86E8
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c2c3c4c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

