#!/bin/bash
# METHOD QM
# ID836ADB6087A920E023CD7C1DB7C2EC6A
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c2c4c5
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

