#!/bin/bash
# METHOD QM
# ID64F55C8CCC34657E84AD9E96870E22B1
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c1c4
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

