#!/bin/bash
# METHOD QM
# IDDCDAE687F913A3EE51872BF30D7760B5
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c1c3c6
prog=lammps
proton=F

 # ---- Script ----

			rm -f energy.dat

