#!/bin/bash
# METHOD QM
# ID6D65AEA2BCF07332BEB31EC21DE1BF7C
# --- Dependencies --- 
. ./DEPENDENCIES
# --- Method Parameters ---
. ./PARAMETERS
molecule=c0c6
prog=lammps
proton=T

 # ---- Script ----

			rm -f energy.dat

